

--DROP TABLE MATERIAL;

CREATE TABLE MATERIAL
(
  ID   BIGINT NOT NULL,
  KODN INTEGER NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  CONSTRAINT PK_MATERIAL PRIMARY KEY (ID)
);

--CREATE UNIQUE INDEX IDX_MATERIAL_KODN ON MATERIAL (KODN);
-- 4. Временно меняем терминатор, чтобы создать триггер
--SET TERM ^ ;
--CREATE OR ALTER TRIGGER MATERIAL_BI FOR MATERIAL
--ACTIVE BEFORE INSERT POSITION 0
--AS
--BEGIN
--  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
--    NEW.ID = NEXT VALUE FOR GEN_MATERIAL_ID;
--END^

-- Возвращаем стандартный терминатор
--SET TERM ; ^

--GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE ON TABLE MATERIAL TO SYSDBA WITH GRANT OPTION;
