-- DROP TABLE MATERIAL_DAY_VALUE;

CREATE TABLE MATERIAL_DAY_VALUE
(
  ID   BIGINT NOT NULL,
  KODN INTEGER NOT NULL,
  MASS DECIMAL(15, 3) NOT NULL,
  DAT  DATE NOT NULL,
  PRIMARY KEY (ID)
);

--CREATE OR ALTER TRIGGER MATERIAL_DAY_VALUE_BI FOR MATERIAL_DAY_VALUE
--ACTIVE BEFORE INSERT POSITION 0
--AS
--BEGIN
--  IF (NEW.ID IS NULL OR NEW.ID = 0) THEN
--    NEW.ID = NEXT VALUE FOR GEN_MATERIAL_DAY_VALUE_ID;
--END;

--GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE ON TABLE MATERIAL_DAY_VALUE TO SYSDBA WITH GRANT OPTION;