CREATE TABLE MATERIAL_AGGREGATED_CORRECTED
(
  ID             BIGINT NOT NULL,
  KODN           INTEGER NOT NULL,
  MASS_CORRECTED DECIMAL(15, 3),
  DAT            DATE NOT NULL,
  "COMMENT"      VARCHAR(255),
  USERNAME       VARCHAR(50),
  CORRECTED_AT   TIMESTAMP,
  PRIMARY KEY (ID)
);

--CREATE OR ALTER TRIGGER BI_MATERIAL_AGG_CORRECTED_ID FOR MATERIAL_AGGREGATED_CORRECTED
--ACTIVE BEFORE INSERT POSITION 0
--AS
--BEGIN
--  IF (NEW.ID IS NULL) THEN
--    NEW.ID = GEN_ID(GEN_MATERIAL_AGG_CORR_ID, 1);
--END;

--GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE ON TABLE MATERIAL_AGGREGATED_CORRECTED TO SYSDBA WITH GRANT OPTION;